all:
	g++ -std=c++11 -fopenmp vector.cpp -o vector
	g++ -std=c++11 -fopenmp array.cpp -o array
	g++ -std=c++11 -fopenmp stack.cpp -o stack
	g++ -std=c++11 -fopenmp queue.cpp -o queue
	g++ -std=c++11 -fopenmp map.cpp -o map
